# Generated by Django 3.2 on 2021-05-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_notified_at',
            field=models.DateTimeField(null=True),
        ),
    ]
